title: "Quarks Volde - Ocean Atmospheric Researcher"
email: workofmine.rahul@gamil.com
description: "Research in ocean-atmospheric climate change and variability"
baseurl: ""
url: "https://quarks-volde.github.io/quarks/"
theme: minima
github_username: quarks-volde

# Social Links
twitter_username: quarksvolde
github_username: quarks-volde

